name: Debug SSH Connection

on:
  push:
    branches: [ main ]

jobs:
  debug:
    runs-on: ubuntu-latest
    
    steps:
    - name: Debug SSH
      run: |
        echo "Setting up SSH key..."
        mkdir -p ~/.ssh
        # Write the key with proper formatting
        echo "${{ secrets.ssh_key }}" | tr -d '\r' > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        
        # Add the host to known_hosts
        ssh-keyscan ${{ secrets.dns_name }} >> ~/.ssh/known_hosts
        
        # Try connection with StrictHostKeyChecking=no
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key ${{ secrets.username }}@${{ secrets.dns_name }} "echo Connection successful"
