name: Debug SSH Connection

on:
  push:
    branches: [ main ]

jobs:
  debug:
    runs-on: ubuntu-latest
    
    steps:
    - name: Debug SSH
      run: |
        echo "Setting up SSH key..."
        mkdir -p ~/.ssh
        echo "${{ secrets.ssh_key }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        echo "Running ssh-keyscan..."
        ssh-keyscan ${{ secrets.dns_name }}
        echo "Trying SSH connection with verbose output..."
        ssh -v -i ~/.ssh/deploy_key ${{ secrets.username }}@${{ secrets.dns_name }} "echo Connection successful"
