name: Calculator CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.ssh_key }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        ssh-keyscan -t rsa ${{ secrets.dns_name }} >> ~/.ssh/known_hosts
    
    - name: Deploy files
      run: |
        ssh -i ~/.ssh/deploy_key ${{ secrets.username }}@${{ secrets.dns_name }} "mkdir -p ${{ secrets.target_dir }}"
        scp -i ~/.ssh/deploy_key CalculatorApp.py main.py ${{ secrets.username }}@${{ secrets.dns_name }}:${{ secrets.target_dir }}/
