name: Calculator CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.dns_name }}
        username: ${{ secrets.username }}
        key: ${{ secrets.ssh_key }}
        script: |
          mkdir -p ${{ secrets.target_dir }}
          
    - name: Copy files to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.dns_name }}
        username: ${{ secrets.username }}
        key: ${{ secrets.ssh_key }}
        source: "CalculatorApp.py,main.py"
        target: ${{ secrets.target_dir }}
